version: "3.9"


networks:
  shared-networks: 

services:
  mongoDB:
    image: mongo:latest
    restart: always
    environment:
      - CONNECING_TO_DB=${CONNECING_TO_DB}
    ports:
    - 27017:27017
    networks:
      - shared-networks
    volumes:
      - ./mongoDB:/var/lib/mongo/data
  server:
    container_name: project-chat-server
    restart: unless-stopped
    image: chat-server:1.0.0
    environment:
      - CONNECING_TO_DB=${CONNECING_TO_DB}
      - FRONT_URL=${FRONT_URL}
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 4000:4000 
    networks:
      - shared-networks
    depends_on:
      - mongoDB
  client:
    container_name: project-chat-client
    restart: unless-stopped
    image: chat-client:1.0.0
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 3000:3000 
    networks:
      - shared-networks
    depends_on:
      - server



 